# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Russell Shepherd
email: russleeshepherd@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a data analyst and technologist based in Manila. I'm interested in using data
  to answer real world questions and how organizations can learn to use data better. I am
  currently CTO of Rappler and Reach Social.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rlshepherd.github.io" # the base hostname & protocol for your site
twitter_username: russellshepherd
github_username:  rlshepherd

# Build settings
markdown: kramdown
